version: 2

jobs:
  build:
    docker:
      - image: docker:17.03.2-ce-git
    working_directory: ~/microservice-movies
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 \
              bash \
              jq \
              curl \
              nodejs
            pip install \
              docker-compose==1.12.0 \
              awscli
      - run:
          name: Build Docker images
          command: |
            IMAGE_TAG=$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
            IMAGE_NAME="$ECR_REPO/$IMAGE_TAG"
            SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            TAG=$SHORT_GIT_HASH
            REPO=$ECR_REPO
            docker build -t $CIRCLE_PROJECT_REPONAME .
            docker tag $CIRCLE_PROJECT_REPONAME:latest $REPO/$IMAGE_TAG
            docker tag $CIRCLE_PROJECT_REPONAME:latest $REPO/$CIRCLE_PROJECT_REPONAME:latest
            $(aws ecr get-login --region us-east-2)
            docker push $REPO/$IMAGE_TAG
            docker push $REPO/$CIRCLE_PROJECT_REPONAME:latest
            
      - run:
          name: Deploy to ECS
          command: |
            pip install ecs-deploy
            ecs deploy --region ${AWS_REGION} ${CLUSTER_NAME} $CIRCLE_PROJECT_REPONAME --tag $CIRCLE_SHA1
