version: 2

jobs:
  build:
    docker:
      - image: docker:17.03.2-ce-git
    working_directory: ~/microservice-movies
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 \
              bash \
              jq \
              curl \
              nodejs
            pip install \
              docker-compose==1.12.0 \
              awscli
      - run:
          name: Build Docker images
          command: |
            SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            TAG=$SHORT_GIT_HASH
            IMAGE_TAG=$CIRCLE_PROJECT_REPONAME:$TAG
            IMAGE_NAME="$ECR_REPO/$IMAGE_TAG"
            REPO=$ECR_REPO
            docker build -t $CIRCLE_PROJECT_REPONAME .
            docker tag $CIRCLE_PROJECT_REPONAME:latest $REPO/$IMAGE_TAG
            docker tag $CIRCLE_PROJECT_REPONAME:latest $REPO/$CIRCLE_PROJECT_REPONAME:latest
            $(aws ecr get-login --region us-east-2)
            docker push $REPO/$IMAGE_TAG
            docker push $REPO/$CIRCLE_PROJECT_REPONAME:latest
            
      - run:
          name: Deploy to ECS
          command: |
            pip install ecs-deploy
            SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            TAG=$SHORT_GIT_HASH
            IMAGE_TAG=$CIRCLE_PROJECT_REPONAME:$TAG
            IMAGE_NAME="$ECR_REPO/$IMAGE_TAG"
            TASK_FAMILY=$CIRCLE_PROJECT_REPONAME
            aws configure set default.region us-east-2
            #aws configure set default.output json
            SERVICE_NAME="ecs-service"
            echo 'sed command   >>';sed -e "s;%IMAGE_TAG%;${TAG};g" ecs-tasks.json > my_website-${BUILD_NUMBER}.json
            echo 'register task >>';aws ecs register-task-definition --family $TASK_FAMILY --cli-input-json file://my_website-${BUILD_NUMBER}.json
            echo 'TASK REV VAR  >>';TASK_REVISION=`aws ecs describe-task-definition --task-definition ${TASK_FAMILY} | egrep "revision" | tr "/" " " | awk '{print $2}' | sed 's/"$//'`
            
            DESIRED_COUNT="1"
            echo 'Update service >>';aws ecs update-service --cluster ${CLUSTER_NAME} --service ${SERVICE_NAME} --task-definition ${TASK_FAMILY}:${TASK_REVISION}
