version: 2

jobs:
  build:
    docker:
      - image: docker:17.03.2-ce-git
    working_directory: ~/microservice-movies
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 \
              bash \
              jq \
              curl \
              nodejs
            pip install \
              docker-compose==1.12.0 \
              awscli
      - run:
         name: test
         command: |
           python test.py
            
      #- run:
      #    name: Build Docker images
      #    command: |
      #      bin/deploy.sh --action=build
            
      #- run:
      #    name: Deploy to ECS
      #    command: |
      #     bin/deploy.sh --action=deploy --cluster=v6-stage3-ECSCluster-1X4SJGQ770EZL --service=ecs-service
